const players = [
    { name: "Jason Houghton" },
    { name: "Mahir Emery" },
    { name: "Jameel Gunn" },
    { name: "Astrid Lara" },
    { name: "Beth Wilder" },
    { name: "Meera Rosales" },
    { name: "Rita Sanderson" },
    { name: "Rosina Cartwright" },
    { name: "Orson Patterson" },
    { name: "Pharrell Taylor" },
    { name: "Xanthe Cooley" },
    { name: "Sheikh Hardin" },
    { name: "Matteo Wynn" },
    { name: "Wilbur Webber" },
    { name: "Ajwa Goff" },
    { name: "Taryn Schaefer" },
    { name: "Zofia Winter" },
    { name: "Colm Erickson" },
    { name: "Erica Blevins" },
    { name: "Allan Rodgers" },
    { name: "Keisha Arroyo" },
    { name: "Angelica Herman" },
    { name: "Darrel Hough" },
    { name: "Clinton Whitehead" },
    { name: "Maiya Holt" },
    { name: "Kaan Velazquez" },
    { name: "Sarina Stewart" },
    { name: "Abid Clegg" },
    { name: "Sean Brennan" },
    { name: "Kerry Moran" },
    { name: "Ayat Wormald" },
    { name: "Izabel Timms" },
    { name: "Roman Cairns" },
    { name: "Wayne Turnbull" },
    { name: "Humayra Meza" },
    { name: "Chelsey French" },
    { name: "Rhiannan Easton" },
    { name: "Fatima Lowry" },
    { name: "Ibraheem Ferry" },
    { name: "Ifan Glass" },
];

module.exports = players;